packages:
  - packages/*

catalog:
  '@anthropic-ai/claude-agent-sdk': ^0.1.23
  '@anthropic-ai/claude-code': ^2.0.24
  '@biomejs/biome': ^2.2.6
  '@effect/platform': ^0.92.1
  '@effect/platform-node': ^0.98.4
  '@hono/node-server': ^1.19.5
  '@hono/zod-validator': ^0.7.4
  '@lingui/cli': ^5.5.1
  '@lingui/conf': ^5.5.1
  '@lingui/core': ^5.5.1
  '@lingui/format-json': ^5.5.1
  '@lingui/loader': ^5.5.1
  '@lingui/react': ^5.5.1
  '@lingui/vite-plugin': ^5.5.1
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-tooltip': ^1.2.8
  '@tailwindcss/postcss': ^4.1.15
  '@tailwindcss/vite': 4.1.16
  '@tanstack/nitro-v2-vite-plugin': ^1.133.19
  '@tanstack/react-devtools': ^0.7.8
  '@tanstack/react-query': ^5.90.5
  '@tanstack/react-router': 1.133.27
  '@tanstack/react-router-devtools': 1.133.27
  '@tanstack/router-plugin': 1.133.27
  '@tsconfig/node20': ^20.1.6
  '@tsconfig/strictest': ^2.0.6
  '@types/node': ^24.9.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@types/react-syntax-highlighter': ^15.5.13
  '@vitejs/plugin-react': 5.1.0
  '@vitejs/plugin-react-swc': ^4.2.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^4.1.0
  dotenv: ^17.2.3
  dotenv-cli: ^10.0.0
  effect: ^3.18.4
  es-toolkit: ^1.40.0
  hono: 4.10.1
  jotai: ^2.15.0
  lucide-react: ^0.546.0
  next: 15.5.6
  next-themes: ^0.4.6
  npm-run-all2: ^8.0.4
  parse-git-diff: ^0.0.19
  playwright: ^1.56.1
  prexit: ^2.3.0
  react: ^19.2.0
  react-dom: ^19.2.0
  react-error-boundary: ^6.0.0
  react-markdown: ^10.1.0
  react-syntax-highlighter: ^15.6.6
  release-it: ^19.0.5
  release-it-pnpm: ^4.6.6
  remark-gfm: ^4.0.1
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.15
  tsx: ^4.20.6
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  ulid: ^3.0.1
  vite: ^7.1.12
  vitest: 3.2.4
  web-vitals: ^5.1.0
  zod: 4.1.12

catalogMode: strict

cleanupUnusedCatalogs: false

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
